trigger:
- main

pool:
  vmImage: ubuntu-latest

variables:
  terraformServiceConnection: 'aws-terraform-Con'

jobs:
- job: CreateRDS
  steps:
  - task: TerraformInstaller@1
    inputs:
      terraformVersion: 'latest'

  - task: TerraformTaskV4@4
    inputs:
      provider: 'aws'
      command: 'init'
      backendServiceAWS: 'aws-terraform-con'
      backendAWSBucketName: 'terraform-aws-br'
      backendAWSKey: 'AKIA3JMZJSW3SHQMJNU4'

